---

- name: Install official common packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ install_common_packages.official }}"
  when: install_common_packages.official
  tags:
    - packages
    - official-packages

- name: Install official group packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ install_group_packages.official }}"
  when: install_group_packages.official
  tags:
    - packages
    - official-packages

- name: Check for ungoogled-chromium package
  shell: pacman -Qi ungoogled-chromium
  register: ungoogled_chromium_installed
  ignore_errors: True
  check_mode: False
  changed_when: False

- name: Install chromium package
  package:
    name: chromium
    state: present
  when: "'personal' in group_names and ungoogled_chromium_installed.rc != 0"

- name: Install official host packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ install_host_packages.official }}"
  when: install_host_packages.official
  tags:
    - packages
    - official-packages

- name: Install host aur packages
  aur:
    name: "{{ item }}"
    use: yay
    skip_installed: true
  become: yes
  become_user: aur_builder
  with_items: '{{ install_host_packages.aur }}'
  when: install_host_packages.aur
  tags:
    - packages
    - aur-packages

- name: Install group aur packages
  aur:
    name: "{{ item }}"
    use: yay
    skip_installed: true
  become: yes
  become_user: aur_builder
  with_items: '{{ install_group_packages.aur }}'
  when: install_group_packages.aur
  tags:
    - packages
    - aur-packages
