fail_fast: true
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: fix-byte-order-marker
  - id: check-merge-conflict
  - id: check-json
  - id: check-yaml
  - id: sort-simple-yaml
  - id: check-xml
  - id: check-merge-conflict
  - id: check-ast
  - id: check-executables-have-shebangs
    exclude: >
      (?x)^(
        .*\.desktop|
      )$
  - id: check-shebang-scripts-are-executable
    exclude: '^.*\.j2$'
  - id: check-toml
  - id: check-added-large-files
  - id: check-symlinks
  - id: destroyed-symlinks
  - id: detect-private-key
  - id: fix-encoding-pragma
    args: [--remove]
  - id: no-commit-to-branch
    args: [--branch, master]
  - id: requirements-txt-fixer
- repo: https://github.com/pre-commit-ci/pre-commit-ci-config
  rev: v1.5.1
  hooks:
  - id: check-pre-commit-ci-config
- repo: https://github.com/pre-commit/pre-commit
  rev: v2.16.0
  hooks:
  - id: validate_manifest
- repo: https://github.com/asottile/reorder_python_imports
  rev: v2.6.0
  hooks:
  - id: reorder-python-imports
    args: [--py39-plus]
- repo: https://github.com/asottile/add-trailing-comma
  rev: v2.2.1
  hooks:
  - id: add-trailing-comma
    args: [--py36-plus]
- repo: https://github.com/asottile/pyupgrade
  rev: v2.31.0
  hooks:
  - id: pyupgrade
    args: [--py39-plus]
- repo: https://github.com/asottile/setup-cfg-fmt
  rev: v1.20.0
  hooks:
  - id: setup-cfg-fmt
ci:
  autofix_prs: false
  autoupdate_commit_msg: 'pre-commit: bump repositories'
