theme = "sonokai"

[editor]
line-number = "relative"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = " "

[editor.indent-guides]
render = true

[keys.normal]
V = ["select_mode", "extend_to_line_bounds"]

o = ["open_below", "normal_mode"]
O = ["open_above", "normal_mode"]

C-left = "move_prev_word_start"
C-right = "move_next_word_end"
C-up = "shrink_selection"
C-down = "expand_selection"

w = ["move_next_word_start", "move_char_right", "collapse_selection"]
e = ["move_next_word_end", "collapse_selection"]
b = ["move_prev_word_start", "collapse_selection"]

"{" = ["goto_prev_paragraph", "collapse_selection"]
"}" = ["goto_next_paragraph", "collapse_selection"]

"^" = "goto_first_nonwhitespace"
"$" = "goto_line_end"

G = "goto_file_end"

d = { d = ["extend_to_line_bounds", "delete_selection"], t = ["extend_till_char"], s = ["surround_delete"], i = ["select_textobject_inner"], a = ["select_textobject_around"] }

x = "delete_selection"
p = "paste_clipboard_after"
P = "paste_clipboard_before"

y = ["yank_main_selection_to_clipboard", "normal_mode", "flip_selections", "collapse_selection"]
Y = ["extend_to_line_bounds", "yank_main_selection_to_clipboard", "goto_line_start", "collapse_selection"]

[keys.insert]
esc = ["collapse_selection", "normal_mode"]

[keys.select]
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]

k = ["extend_line_up", "extend_to_line_bounds"]
j = ["extend_line_down", "extend_to_line_bounds"]
"up" = ["extend_line_up", "extend_to_line_bounds"]
"down" = ["extend_line_down", "extend_to_line_bounds"]

"{" = ["extend_to_line_bounds", "goto_prev_paragraph"]
"}" = ["extend_to_line_bounds", "goto_next_paragraph"]

"^" = "goto_first_nonwhitespace"
"$" = "goto_line_end"

S = "surround_add"
