---

- name: remove iptables package
  pacman:
    name: iptables
    state: absent
    force: yes
  tags:
    - libvirt

- name: install ebtables package
  pacman:
    name: ebtables
    state: present
  tags:
    - libvirt

- name: install libvirt and dependencies
  pacman:
    name:
      - libvirt
      - qemu
      - openbsd-netcat
      - dnsmasq
      - bridge-utils
      - dmidecode
      - edk2-ovmf
      - swtpm
    state: present
  tags:
    - libvirt

- name: add libvirt group
  group:
    name: libvirt
    state: present
  tags:
    - libvirt

# https://github.com/ansible/ansible/issues/11024
- name: remove all users from libvirt group
  command: groupmems -g libvirt --purge
  tags:
    - libvirt

- name: add admin users to libvirt
  user:
    name: '{{ item.key }}'
    append: yes
    groups: libvirt
  with_dict: '{{ users }}'
  when: '"admin" in item.value.groups'
  tags:
    - libvirt

- name: install libvirt configs
  template:
    src: '{{ item }}'
    dest: '/etc/libvirt/{{ item }}'
    mode: 0644
    owner: root
    group: root
  with_items:
    - libvirtd.conf.j2
  tags:
    - libvirt

- name: activate libvirtd service
  service:
    name: libvirtd
    enabled: yes
    state: restarted
  tags:
    - libvirt
