---

- name: remove iptables package
  pacman:
    name: iptables
    state: absent
    force: yes
  tags:
    - libvirt

- name: install ebtables package
  pacman:
    name: ebtables
    state: present
  tags:
    - libvirt

- name: install libvirt and dependencies
  pacman:
    name:
      - libvirt
      - qemu
      - openbsd-netcat
      - dnsmasq
      - bridge-utils
      - dmidecode
      - swtpm
    state: present
  tags:
    - libvirt

- name: install libvirt UEFI support
  pacman:
    name: edk2-ovmf
    state: present
  tags:
    - libvirt
  when: inventory_hostname != 'pie'

- name: install libvirt configs
  template:
    src: '{{ item }}'
    dest: '/etc/libvirt/{{ item }}'
    mode: 0644
    owner: root
    group: root
  with_items:
    - libvirtd.conf.j2
  tags:
    - libvirt

- name: activate libvirtd service
  service:
    name: libvirtd
    enabled: yes
    state: restarted
  tags:
    - libvirt
