---

- name: install lightdm package
  pacman:
    name:
      - lightdm
      - lightdm-gtk-greeter
    state: present
  tags:
    - desktopenv

# FIXME: Check for lightdm-plymouth

# - name: activate lightdm service
#   service:
#     name: lightdm
#     enabled: yes
#     state: started
#   tags:
#     - desktopenv
