---

- name: install openssh
  pacman:
    name: openssh
    state: present
  tags: sshd

- name: install sshd_config
  template: src=sshd_config.j2 dest=/etc/ssh/sshd_config owner=root group=root mode=0644
  tags: sshd

- name: start and enable sshd
  service: name=sshd enabled=yes state=started
  when: ansible_connection != 'local'
  tags: sshd

- name: only enable sshd
  service: name=sshd enabled=yes
  when: ansible_connection == 'local'
  tags: sshd

