---

- name: Setup machines
  hosts:
    - mars
    - deimos
    - tornado
    - localhost
  remote_user: root
  roles:
    - { role: users, tags: ['users'] }
    - { role: sudo, tags: ['sudo']}
    - { role: base, tags: ['base'] }
    - role: hardening
      tags: ['hardening']
      when: "'servers' in group_names"

    # Available subtags: powertop, ipmitool
    - role: powersave
      tags: ['powersave']
      when: "'servers' in group_names"

    - { role: packages, tags: ['packages'] }
    - { role: archbuild, tags: ['archbuild'] }
    - role: syncrepo
      tags: ['syncrepo']
      when: "'servers' in group_names"

    # Available subtags: docker, podman
    - { role: containers, tags: ['containers'] }

    # Optional: please provide usersbox tag to explicitly deploy this
    - role: usersbox
      when: ansible_hostname == 'tornado'

