---

- name: Setup box machines
  hosts:
    - localhost
  remote_user: root
  roles:
    - { role: facts, tags: ['facts'] }
    - { role: users, tags: ['users'] }
    - { role: sudo, tags: ['sudo']}
    - { role: sshd, tags: ['sshd'] }
    - { role: base, tags: ['base'] }
    - { role: yay, tags: ['yay'] }
    - { role: packages, tags: ['packages'] }
