---

- name: Setup private machines
  hosts:
    - tortoise
  remote_user: root
  roles:
    - { role: facts, tags: ['facts'] }
    - { role: users, tags: ['users'] }
    - { role: sudo, tags: ['sudo']}
    - { role: sshd, tags: ['sshd'] }
    - { role: base, tags: ['base'] }
    - { role: locale, tags: ['locale'] }
    - { role: packages, tags: ['packages'] }
    - { role: hardening, tags: ['hardening'] }
    - { role: firewall, tags: ['firewall'] }

    - role: tor
      tags: ['tor']
      when: ansible_hostname == 'tortoise'
