---

- name: Setup machines
  hosts:
    - mars
    - deimos
    - tornado
    - pie
  remote_user: root
  roles:
    - { role: facts, tags: ['facts'] }
    - { role: users, tags: ['users'] }
    - { role: sudo, tags: ['sudo']}
    - { role: sshd, tags: ['sshd'] }
    - { role: base, tags: ['base'] }
    - { role: locale, tags: ['locale'] }

    - role: hardening
      tags: ['hardening']
      when: "'servers' in group_names"

    # Available subtags: powertop, ipmitool
    - role: powersave
      tags: ['powersave']
      when: "'servers' in group_names"

    - { role: archbuild, tags: ['archbuild'] }
    - { role: yay, tags: ['yay'] }
    - { role: packages, tags: ['packages'] }

    - role: syncrepo
      tags: ['syncrepo']
      when: ansible_hostname == 'tornado'

    # Available subtags: docker, podman
    - { role: containers, tags: ['containers'] }

    # Optional: please provide usersbox_full tag to explicitly deploy this
    # fully. This is needed because copying the docker container on every
    # deploy is costly.
    - role: usersbox
      when: ansible_hostname == 'tornado'

    - { role: kvm, tags: ['kvm'] }
    - { role: libvirt, tags: ['libvirt'] }

    - role: desktopenv
      tags: ['desktopenv']
      when: ansible_hostname in ['mars', 'deimos']
