name: cron-checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # Every day
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  docker-build-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        cd deploy/docker;
        docker build ../../ --file Dockerfile --tag localbuild/testimage:latest
    - name: Run the Anchore scan
      # continue-on-error: true
      uses: anchore/scan-action@v3.2.1
      with:
        image: "localbuild/testimage:latest"
        debug: true
        fail-build: false
        severity-cutoff: critical
        acs-report-enable: true
    - name: Upload Anchore Scan Report
      uses: github/codeql-action/upload-sarif@v1
      continue-on-error: true
      with:
        sarif_file: results.sarif
