name: cron-checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # Every day
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  docker-build-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v3.1.0
    - name: Checkout submodules
      run: |
        git submodule sync
        git -c protocol.version=2 submodule update --init --force --depth=1 3rdparty/
    - if: github.event_name != 'pull_request'
      name: Login to DockerHub
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build the Docker image
      run: |
        cd deploy/docker/devbox
        docker build ../../../ --file Dockerfile --tag ljmf00/devbox:latest
        cd ../userbox
        docker build ../../../ --file Dockerfile --tag ljmf00/userbox:latest
    - name: Run the Anchore scan
      # continue-on-error: true
      uses: anchore/scan-action@v3.3.1
      with:
        image: "ljmf00/userbox:latest"
        debug: true
        fail-build: false
        severity-cutoff: critical
        acs-report-enable: true
    - name: Upload Anchore Scan Report
      uses: github/codeql-action/upload-sarif@v2
      continue-on-error: true
      with:
        sarif_file: results.sarif
    - if: github.event_name != 'pull_request'
      name: Push docker images
      run: |
        docker push ljmf00/devbox:latest
        docker push ljmf00/userbox:latest
