name: dotfiles

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  configure:
    strategy:
      matrix:
        workspace:
          - generic
          - personal
          - work
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ljmf00/archlinux:aur
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    steps:
    - uses: actions/checkout@v3.5.2
    - name: Checkout submodules
      run: |
        # inside the container git --global configuration isn't set
        git config --global --add safe.directory '*'

        git submodule sync
        git -c protocol.version=2 submodule update --init --force --depth=1 3rdparty/
    - name: Install dependencies
      run: |
        pacman -Syyu --needed --noconfirm --noprogressbar \
          bind-tools xdg-utils rsync sudo stow git docker docker-compose docker-buildx

        dbus-uuidgen --ensure=/etc/machine-id
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2.2.0
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2.7.0
      with:
        version: 'latest'
        driver-opts: |
          network=host
          image=moby/buildkit:latest
    - name: Run dotfiles configuration script w/ minimal installation
      run: |
        useradd -g users -G wheel -m luis
        echo "${{ matrix.workspace }}" > /etc/hostname
        chown -R luis:users .
        sudo -u luis bash -c 'rm -rf ~/.bash*'
        sudo -u luis ./configure
        sudo -u luis ./configure install
    - name: Install neovim dependencies
      if: matrix.workspace == 'personal'
      run: |
        pacman -Syy --needed --noconfirm --noprogressbar \
          neovim go python python-pip python-pynvim
        # Required by coq.nvim
        sudo -u luis bash -c 'mkdir -p ~/.local/share/nvim/site/pack/packer/start/'
        sudo -u luis bash -c 'echo -e "[settings]\napi_key = 00000000-0000-0000-0000-000000000000" > ~/.wakatime.cfg'
    - name: Install neovim extensions and try to start it
      if: matrix.workspace == 'personal'
      timeout-minutes: 15
      run: |
        # Packer install and sync
        echo "--> Packer install"
        sudo -u luis nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerInstall'
        # FIXME: Sync doesn't work
        # echo "--> Packer sync"
        # sudo -u luis nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
        echo "--> Try to open and exit"
        sudo -u luis nvim --headless -c 'quitall'
