name: dotfiles

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  configure:
    strategy:
      matrix:
        workspace:
          - personal
          - work
    runs-on: ubuntu-latest
    container: ghcr.io/ljmf00/archlinux:aur
    steps:
    - uses: actions/checkout@v3.5.2
    - name: Checkout submodules
      run: |
        # inside the container git --global configuration isn't set
        git config --global --add safe.directory "$(pwd)"

        git submodule sync
        git -c protocol.version=2 submodule update --init --force --depth=1 3rdparty/
    - name: Run dotfiles configuration script w/ minimal installation
      run: |
        pacman -Syy --needed --noconfirm --noprogressbar \
          bind-tools xdg-utils rsync sudo
        useradd -g users -G wheel -m luis
        sudo -u luis bash -c 'DOTFILES_WORKSPACE="${{ matrix.workspace }}" ./configure.sh'
    - name: Install neovim dependencies
      if: matrix.workspace == 'personal'
      run: |
        pacman -Syy --needed --noconfirm --noprogressbar \
          neovim go python python-pip
        sudo -u luis pip install --user neovim
        # Required by coq.nvim
        sudo -u luis bash -c 'mkdir -p ~/.local/share/nvim/site/pack/packer/start/'
        sudo -u luis bash -c 'git clone https://github.com/ms-jpq/coq_nvim.git ~/.local/share/nvim/site/pack/packer/start/coq_nvim'
        sudo -u luis bash -c 'cd ~/.local/share/nvim/site/pack/packer/start/coq_nvim && python -m coq deps'
        sudo -u luis bash -c 'echo -e "[settings]\napi_key = 00000000-0000-0000-0000-000000000000" > ~/.wakatime.cfg'
    - name: Install neovim extensions and try to start it
      if: matrix.workspace == 'personal'
      timeout-minutes: 15
      run: |
        # Packer install and sync
        echo "--> Packer install"
        sudo -u luis nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerInstall'
        # FIXME: Sync doesn't work
        # echo "--> Packer sync"
        # sudo -u luis nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
        echo "--> Try to open and exit"
        sudo -u luis nvim --headless -c 'quitall'
