name: webapp

on:
  pull_request:
    branches:
      - master
    paths:
    - 'webapp/**'
    - '.github/workflows/webapp.yml'
    - '.pre-commit-config.yaml'
  push:
    branches:
      - master
    paths:
    - 'webapp/**'
    - '.github/workflows/webapp.yml'
    - '.pre-commit-config.yaml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/ljmf00/archlinux:aur
    steps:
    - uses: actions/checkout@v3.5.2
    - name: Install dependencies
      run: |
        pacman -Syyu --needed --noconfirm --noprogressbar \
          nodejs yarn composer php
    - name: Build
      run: |
        cd webapp

        composer install
        yarn install
        yarn run build
