name: webapp

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/ljmf00/archlinux:aur
    steps:
    - uses: actions/checkout@v3.5.2
    - name: Install dependencies
      run: |
        pacman -Syy --needed --noconfirm --noprogressbar \
          nodejs npm composer php icu lib32-icu
    - name: Build
      run: |
        cd webapp

        composer install
        npm install
        npm run build
